//Brian Hodge
//C00170400
//CMPS 260
//Programming Assignment: #9
//Due Date: 05/03/2019
//Program Description: This program prompts the user to enter a positive integer, then passes that integer to a
// recursive function to print out n amount of '*' with n being the integer that the user enters. Next the user is
//prompted to enter a string and another positive integer then it outputs the string n amunt of times based on the
//value of the integer entered via a recursive method.
//Certificate of Authenticity: I certify that the code of this project, other than that that was generated by IntelliJ,
//is entirely my own work.

package com.company;

import java.util.Scanner;

public class Main {

    public static void main(String[] args) {

        Scanner input = new Scanner(System.in);
        System.out.print("Enter a positive integer: ");
        carot(input.nextInt());
        System.out.println();
        input.nextLine();
        System.out.print("Enter a String: ");
        String message = input.nextLine();
        System.out.print("Enter a positive integer: ");
        recursiveString(input.nextInt(), message);


    }

    public static void carot(int value) {
        if (value >= 1) {
            System.out.print("*");
            carot(value - 1);
        }
    }

    public static void recursiveString(int value, String s) {
        if (value >= 1) {
            System.out.println(s);
            recursiveString(value - 1, s);
        }
    }
}
